version: "3.1"
services:
  frontend:
    build: 
      context: ./storefront
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./storefront:/app
    env_file:
      - ./storefront/.env

  api:
    build: 
      context: ./storefront-api
      dockerfile: Dockerfile   
    ports:
      - "4000:4000"
    volumes:
      - ./storefront-api:/app
    env_file:
      - ./storefront-api/.env
